[package]
name = "tagr"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
clap = { version = "4.5.51", features = ["derive"] }
dirs = "6.0.0"
rusqlite = "0.37.0"
serde = { version = "1.0.228", features = ["derive"] }
skim = "0.20.5"
sled = "0.34.7"
thiserror = "2.0.17"
