[advisories]
ignore = [
    "RUSTSEC-2026-0001", # rkyv potential undefined behavior - dependency is unused
    "RUSTSEC-2025-0057", # fxhash unmaintained - via sled
    "RUSTSEC-2024-0384", # instant unmaintained - via sled
    "RUSTSEC-2024-0320"  # yaml-rust unmaintained - via syntect
]
